import React, { useEffect, useState, useRef } from 'react';
import { api } from '../utils/api';
import { useAuth } from '../context/AuthContext';

const MONTHS = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];

export default function Invoices() {
  const { company } = useAuth();
  const [month,   setMonth]   = useState(new Date().getMonth() + 1);
  const [year,    setYear]    = useState(new Date().getFullYear());
  const [data,    setData]    = useState({ invoices:[] });
  const [loading, setLoading] = useState(true);
  const [preview, setPreview] = useState(null);

  const load = async () => {
    setLoading(true);
    const d = await api.getInvoices(month, year).catch(() => ({ invoices:[] }));
    setData(d);
    setLoading(false);
  };

  useEffect(() => { load(); }, [month, year]);

  const total_pending   = (data.invoices||[]).filter(i => i.payment_status !== 'paid').length;
  const total_collected = (data.invoices||[]).filter(i => i.payment_status === 'paid').reduce((a,i) => a + (i.amount||0), 0);

  const printInvoice = (inv) => {
    const win = window.open('', '_blank');
    const logo  = company?.pg_logo || '🏠';
    const cname = company?.company_name || 'PGease';
    const addr  = company?.address || '';
    const phone = company?.contact_phone || '';
    const total = (inv.amount||0) + (inv.utility_amount||0) + (inv.penalty||0);
    win.document.write(`
      <html><head><title>Invoice #${inv.payment_id||'DRAFT'}</title>
      <style>body{font-family:sans-serif;padding:40px;color:#1e293b}table{width:100%;border-collapse:collapse}td,th{padding:10px;border:1px solid #e2e8f0;font-size:13px}th{background:#f8fafc;font-weight:700}.total{font-size:16px;font-weight:800}.accent{color:#FF6B35}</style></head>
      <body>
        <div style="display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:32px">
          <div><div style="font-size:32px">${logo}</div><div style="font-size:22px;font-weight:800">${cname}</div><div style="font-size:12px;color:#64748b">${addr} ${phone}</div></div>
          <div style="text-align:right"><div style="font-size:22px;font-weight:800">RENT INVOICE</div><div style="font-size:13px;color:#64748b">Month: ${MONTHS[month-1]} ${year}</div><div style="font-size:13px;color:#64748b">Date: ${new Date().toLocaleDateString('en-IN')}</div></div>
        </div>
        <div style="display:grid;grid-template-columns:1fr 1fr;gap:24px;margin-bottom:24px">
          <div><div style="font-weight:700;margin-bottom:6px">Billed To</div><div style="font-size:15px;font-weight:800">${inv.resident_name}</div><div style="font-size:13px;color:#64748b">${inv.phone||''}</div><div style="font-size:13px;color:#64748b">${inv.email||''}</div></div>
          <div><div style="font-weight:700;margin-bottom:6px">Room Details</div><div style="font-size:15px;font-weight:800">Room ${inv.room_number}</div><div style="font-size:13px;color:#64748b">Type: ${inv.room_type||'—'}</div><div style="font-size:13px;color:#64748b">Move-in: ${inv.move_in_date||'—'}</div></div>
        </div>
        <table><tr><th>Description</th><th>Amount</th></tr>
          <tr><td>Monthly Rent — ${MONTHS[month-1]} ${year}</td><td>₹${(inv.rent_amount||inv.amount||0).toLocaleString()}</td></tr>
          ${inv.electricity_amount > 0 ? `<tr><td>Electricity Charges</td><td>₹${inv.electricity_amount.toLocaleString()}</td></tr>` : ''}
          ${inv.water_amount > 0 ? `<tr><td>Water Charges</td><td>₹${inv.water_amount.toLocaleString()}</td></tr>` : ''}
          ${inv.other_amount > 0 ? `<tr><td>Other Utility Charges</td><td>₹${inv.other_amount.toLocaleString()}</td></tr>` : ''}
          ${(inv.penalty||0) > 0 ? `<tr><td style="color:#ef4444">Late Payment Penalty</td><td style="color:#ef4444">₹${inv.penalty.toLocaleString()}</td></tr>` : ''}
          <tr><td class="total">Total Due</td><td class="total accent">₹${total.toLocaleString()}</td></tr>
        </table>
        <div style="margin-top:24px;padding:16px;background:#f8fafc;border-radius:8px;font-size:12px;color:#64748b">
          Payment Status: <strong style="color:${inv.payment_status==='paid'?'#22c55e':'#f59e0b'}">${(inv.payment_status||'PENDING').toUpperCase()}</strong>
          ${inv.paid_date ? `· Paid on ${inv.paid_date}` : ''}
        </div>
        <div style="margin-top:40px;font-size:11px;color:#94a3b8;text-align:center">Generated by PGease · ${cname}</div>
      </body></html>
    `);
    win.document.close();
    win.print();
  };

  return (
    <div>
      {/* Controls */}
      <div style={{ display:'flex', gap:12, alignItems:'center', marginBottom:20, flexWrap:'wrap' }}>
        <select value={month} onChange={e => setMonth(Number(e.target.value))} className="form-input" style={{ width:120 }}>
          {MONTHS.map((m,i) => <option key={m} value={i+1}>{m}</option>)}
        </select>
        <input type="number" value={year} onChange={e => setYear(Number(e.target.value))} className="form-input" style={{ width:90 }} />
        <div style={{ marginLeft:'auto', display:'flex', gap:20 }}>
          <div style={{ textAlign:'right' }}>
            <div style={{ fontSize:11, color:'var(--text-3)' }}>Pending Invoices</div>
            <div style={{ fontSize:18, fontWeight:800, color:'#f59e0b' }}>{total_pending}</div>
          </div>
          <div style={{ textAlign:'right' }}>
            <div style={{ fontSize:11, color:'var(--text-3)' }}>Collected</div>
            <div style={{ fontSize:18, fontWeight:800, color:'#22c55e' }}>₹{total_collected.toLocaleString()}</div>
          </div>
        </div>
      </div>

      {loading ? <div className="spinner-wrap"><div className="spinner" /></div> : (
        <div className="card" style={{ padding:0, overflow:'hidden' }}>
          <table style={{ width:'100%', borderCollapse:'collapse' }}>
            <thead>
              <tr style={{ background:'var(--bg-hover)' }}>
                {['Room','Resident','Rent (₹)','Utility (₹)','Penalty (₹)','Total (₹)','Status','Actions'].map(h => (
                  <th key={h} style={{ padding:'12px 14px', textAlign:'left', fontSize:11, fontWeight:700, color:'var(--text-3)', textTransform:'uppercase', whiteSpace:'nowrap' }}>{h}</th>
                ))}
              </tr>
            </thead>
            <tbody>
              {(data.invoices||[]).map(inv => {
                const total = (inv.amount||0) + (inv.utility_amount||0) + (inv.penalty||0);
                return (
                  <tr key={inv.resident_id} style={{ borderTop:'1px solid var(--border)' }}>
                    <td style={{ padding:'12px 14px', fontWeight:700 }}>Room {inv.room_number}</td>
                    <td style={{ padding:'12px 14px' }}>
                      <div style={{ fontWeight:600 }}>{inv.resident_name}</div>
                      <div style={{ fontSize:11, color:'var(--text-3)' }}>{inv.phone}</div>
                    </td>
                    <td style={{ padding:'12px 14px' }}>₹{(inv.amount||inv.rent_amount||0).toLocaleString()}</td>
                    <td style={{ padding:'12px 14px' }}>₹{(inv.utility_amount||0).toLocaleString()}</td>
                    <td style={{ padding:'12px 14px', color:'#f59e0b' }}>₹{(inv.penalty||0).toLocaleString()}</td>
                    <td style={{ padding:'12px 14px', fontWeight:800, color:'var(--accent)' }}>₹{total.toLocaleString()}</td>
                    <td style={{ padding:'12px 14px' }}>
                      <span style={{
                        padding:'3px 10px', borderRadius:20, fontSize:11, fontWeight:700,
                        background: inv.payment_status==='paid' ? '#22c55e18' : '#f59e0b18',
                        color:      inv.payment_status==='paid' ? '#22c55e'   : '#f59e0b'
                      }}>{inv.payment_status === 'paid' ? 'Paid' : 'Pending'}</span>
                    </td>
                    <td style={{ padding:'12px 14px' }}>
                      <button className="btn btn-ghost btn-sm" onClick={() => printInvoice(inv)}>🖨 Print</button>
                    </td>
                  </tr>
                );
              })}
              {(data.invoices||[]).length === 0 && (
                <tr><td colSpan={8} style={{ padding:40, textAlign:'center', color:'var(--text-3)' }}>No active residents for this month</td></tr>
              )}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );
}
